from django.db import models
import string
import random

# Create your models here. #Fat models and thin views

# Perfom database operations with Python code


# Generate unique code for each room
def generate_unique_code():
    length = 6

    while True:
        code = ''.join(random.choices(string.ascii_uppercase, k=length))
        # Check if any of the rooms have the code generated and break only if unique
        if Room.objects.filter(code=code).count() == 0:
            break

    return code

# Room model
class Room(models.Model):
    # Unique code to identify the room of maximum 8 char length
    # Concatenate empty string on default with the code generated by generate_unique_co
    code = models.CharField(max_length=8, default="", unique=True)
   # One host per room
    host = models.CharField(max_length=50, unique=True)
    # Prevent the guest from pausing the music
    guest_can_pause = models.BooleanField(null=False, default=False)
    # Allow guests to vote to skip the song playing
    votes_to_skip = models.IntegerField(null=False, default=1)
   # Automatically record the date and time the room was created
    created_at = models.DateTimeField(auto_now_add=True)
